version: '2'
services:
  webserver:
    image: phpstorm/php-apache:8.2-xdebug3.2
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal